### PR TITLE
Course Section Enhancement 

### PR DESCRIPTION
**Pull request by MuhammadZeeshanAshraf**
- chore: added some websites to courses section

### CODE REVIEW

**Comment by jordan-cutler** [comment]
@MuhammadZeeshanAshraf would you be open to creating a new section called "Course sites" and then have these in there?

```
### Course sites
- [Udemy courses](https://www.udemy.com/)
- [Educative subscription](https://www.educative.io/)
- [Pluralsight courses](https://www.pluralsight.com/)
- [Udacity courses](https://www.udacity.com/)
- [Coursera courses](https://www.coursera.org/)
- [Linkedin Learning](https://www.linkedin.com/learning/)
- [Future Learn](https://www.futurelearn.com/subjects/it-and-computer-science-courses)
- [edX](https://www.edx.org/)
- [Microsoft Learn](https://learn.microsoft.com/en-us/)
```

That way there's a list of course sites but also specifically recommended courses, potentially from those sites at the top

**Review by jordan-cutler — CHANGES_REQUESTED** [review]
1 request. Let me know your thoughts

**Comment by MuhammadZeeshanAshraf** [comment]
I believe we would divide the course section into two 
like one for "Top Courses" or the second one for "Recommend Website"

**Comment by jordan-cutler** [comment]
@MuhammadZeeshanAshraf that works for me

**Pull request closed without merging**
